= Términos y condiciones

Con el objetivo de crear una comunidad lo más inclusiva posible y limitar al máximo comportamientos nocivos 
que vayan en contra de nuestro código de conducta, este documento describe una serie de condiciones orientadas
a personas que deseen proponer, impartir, facilitar u organizar cualquier actividad bajo el paraguas de comunidad-groovy
y que deben ser de obligado cumplimiento durante el transcurso de la misma:

- Cumplir con todos los puntos del código de conducta de la comunidad.
- Utilizar un lenguaje lo más inclusivo posible (por ejemplo, limitando siempre que sea posible el uso continuado de pronombres masculinos).
- Mantener una conducta profesional y respetuosa ante las personas que participen en la actividad o envíen sus dudas de manera online.
- NO cambiar la orientación de la actividad sin previo aviso a la organización (que deberá validar el _nuevo_ enfoque).
- Por defecto, las charlas durarán un máximo de 50 minutos
- Las actividades podrán serán grabadas y quedarán subidas al canal de youtube salvo que el o la ponente indique lo contrario. 
